# Wikipedia-Aktionswoche
[aktionswoche]
campaign_tracking = "WMDE_wp20_aw"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[aktionswoche.banners.ctrl]
filename = "./wikipedia_aktionswoche/banner_ctrl.js"
pagename = "B21WMDE_wp20_aw_b1_desktop"
tracking = "WMDE_wp20_aw_b1_desktop"

[aktionswoche.banners.var]
filename = "./wikipedia_aktionswoche/banner_var.js"
pagename = "B21WMDE_wp20_aw_b2_desktop"
tracking = "WMDE_wp20_aw_b2_desktop"

[aktionswoche_mobile]
campaign_tracking = "WMDE_wp20_aw"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[aktionswoche_mobile.banners.ctrl]
filename = "./wikipedia_aktionswoche/banner_ctrl.js"
pagename = "B21WMDE_wp20_aw_b1_mobile"
tracking = "WMDE_wp20_aw_b1_mobile"

[aktionswoche_mobile.banners.var]
filename = "./wikipedia_aktionswoche/banner_var.js"
pagename = "B21WMDE_wp20_aw_b2_mobile"
tracking = "WMDE_wp20_aw_b2_mobile"

[aktionswoche_ipad]
campaign_tracking = "WMDE_wp20_aw"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[aktionswoche_ipad.banners.ctrl]
filename = "./wikipedia_aktionswoche/banner_ctrl.js"
pagename = "B21WMDE_wp20_aw_b1_ipad"
tracking = "WMDE_wp20_aw_b1_ipad"

[aktionswoche_ipad.banners.var]
filename = "./wikipedia_aktionswoche/banner_var.js"
pagename = "B21WMDE_wp20_aw_b2_ipad"
tracking = "WMDE_wp20_aw_b2_ipad"

# Wikipedia-Challenge
[challenge]
campaign_tracking = "WMDE_neweditors_autumn_2019"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[challenge.banners.ctrl]
filename = "./wikipedia_challenge/banner_ctrl.js"
pagename = "B20WMDE_challengebnr_fall2020_ctrl"
tracking = "WMDE_challengebnr_fall2020_ctrl"

[challenge.banners.var]
filename = "./wikipedia_challenge/banner_var.js"
pagename = "B20WMDE_challengebnr_fall2020_var"
tracking = "WMDE_challengebnr_fall2020_var"

[challenge_mobile]
campaign_tracking = "WMDE_neweditors_autumn_2019_m"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[challenge_mobile.banners.var]
filename = "./wikipedia_challenge/banner_var.js"
pagename = "B20WMDE_challengebnr_fall2020_var_m"
tracking = "WMDE_challengebnr_fall2020_var_m"

[challenge_mobile.banners.ctrl]
filename = "./wikipedia_challenge/banner_ctrl.js"
pagename = "B20WMDE_challengebnr_fall2020_ctrl_m"
tracking = "WMDE_challengebnr_fall2020_ctrl_m"

# Occasional Editors Campaign
[occasional]
campaign_tracking = "WMDE_oceditors_spring_2020"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[occasional.banners.ctrl_a]
filename = "./occasional_editors/banner_ctrl.js"
pagename = "B20WMDE_oceditors_spring_2020_ctrl_a"
tracking = "WMDE_oceditors_spring_2020_ctrl"
test_flags = "logged_in|group_a"

[occasional.banners.ctrl_b]
filename = "./occasional_editors/banner_ctrl.js"
pagename = "B20WMDE_oceditors_spring_2020_ctrl_b"
tracking = "WMDE_oceditors_spring_2020_ctrl"
test_flags = "logged_in|group_b"

[occasional.banners.var_a]
filename = "./occasional_editors/banner_var.js"
pagename = "B20WMDE_oceditors_spring_2020_var_a"
tracking = "WMDE_oceditors_spring_2020_var"
test_flags = "logged_in|group_a"

[occasional.banners.var_b]
filename = "./occasional_editors/banner_var.js"
pagename = "B20WMDE_oceditors_spring_2020_var_b"
tracking = "WMDE_oceditors_spring_2020_var"
test_flags = "logged_in|group_b"

# Techwish Campaign
[techwish]
campaign_tracking = "WMDE_techwish_voting_2020"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[techwish.banners.main]
filename = "./techwish/main.js"
pagename = "B20WMDE_techwish_voting_01_200706_main"
#tracking string gets extended with a suffix in the code
tracking = "WMDE_techwish_voting_2020_main"


# Authors Campaign
[authors]
campaign_tracking = "WMDE_neweditors_autumn_2019"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[authors.banners.autumn]
filename = "./authors/banner.js"
pagename = "B19WMDE_neweditors_autumn_2019_lp1"
tracking = "WMDE_neweditors_autumn_2019_lp1"

# Authors Campaign Mobile for easily testing mobile view
[authors_mobile]
campaign_tracking = "WMDE_neweditors_autumn_2019m"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[authors_mobile.banners.autumn]
filename = "./authors/banner_mobile.js"
pagename = "B19WMDE_neweditors_autumn_2019_lp1m"
tracking = "WMDE_neweditors_autumn_2019_lp1m"
